CREATE TABLE ROOM
(
    ROOM_ID NUMBER(15) NOT NULL,
    ROOMTYPE VARCHAR(25),
    PRIMARY KEY (ROOM_ID)
);

CREATE TABLE PRESCRIPTION
(
    PRES_ID NUMBER(15) NOT NULL,
    PRES_PRICE NUMBER(15) NOT NULL,
    PRES_QUANTITY NUMBER(10) NOT NULL,
    PRIMARY KEY (PRES_ID)
);

CREATE TABLE SERVICE
(
    SERVICEID NUMBER(15) NOT NULL,
    SER_TYPE VARCHAR(50),
    PRIMARY KEY (SERVICEID)
);

CREATE TABLE BILL
(
    BILLID NUMBER(15) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    COST NUMBER(10) NOT NULL,
    PRIMARY KEY (BILLID)
);

CREATE TABLE STAFF
(
    STAFF_ID NUMBER(15) NOT NULL,
    STAFF_NAME VARCHAR(20) NOT NULL,
    STAFF_GENDER VARCHAR(2) NOT NULL,
    QUALIFICATION VARCHAR(20) NOT NULL,
    CONTACT VARCHAR(15) NOT NULL,
    PRIMARY KEY (STAFF_ID)
);

CREATE TABLE PATIENT
(
    fname VARCHAR (250) NOT NULL,
    lname VARCHAR (250) NOT NULL,
    contact number (15) NOT NULL,
    PID NUMBER(15) NOT NULL,
    GENDER VARCHAR(2) NOT NULL,
    ADRESS VARCHAR(150),
    PDETAILS VARCHAR(100),
    BLOODGROUP VARCHAR(2) NOT NULL,
    SERVICEID NUMBER(15),
    BILLID NUMBER(15),
    PRIMARY KEY (PID),
    FOREIGN KEY (SERVICEID) REFERENCES SERVICE(SERVICEID),
    FOREIGN KEY (BILLID) REFERENCES BILL(BILLID)
);

CREATE TABLE RECEPTIONIST
(
    REC_ID NUMBER(15) NOT NULL,
    REC_NAME VARCHAR(20) NOT NULL,
    REC_LOC VARCHAR(50) NOT NULL,
    STAFF_ID NUMBER(15) NOT NULL,
    PRIMARY KEY (REC_ID),
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
);

CREATE TABLE APPOINTMENT
(
    PID NUMBER(15) NOT NULL,
    APP_date DATE NOT NULL,
    APP_ID NUMBER(15) NOT NULL,
    ROOM_ID NUMBER(15) NOT NULL,
    STAFF_ID NUMBER(15) NOT NULL,
    SERVICEID NUMBER(15) NOT NULL,
    REC_ID NUMBER(15),
    PRIMARY KEY (APP_ID),
    FOREIGN KEY (PID) REFERENCES PATIENT(PID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID),
    FOREIGN KEY (SERVICEID) REFERENCES SERVICE(SERVICEID),
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
);

CREATE TABLE RECORD
(
    PID NUMBER(15) NOT NULL,
    RECORD_# NUMBER(15) NOT NULL,
    APP_ID NUMBER(15) NOT NULL,
    FOREIGN KEY (PID) REFERENCES PATIENT(PID),
    PRIMARY KEY (RECORD_#),
    FOREIGN KEY (APP_ID) REFERENCES APPOINTMENT(APP_ID)
);


CREATE TABLE users
(
    email varchar(250) NOT NULL,
    PASSWORD VARCHAR(100),
    STAFF_ID NUMBER(15),
    PID NUMBER(15),
    PRIMARY KEY (email)
);

CREATE SEQUENCE  pnum  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE  appointnum  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE  billnum  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1;
